[package]
name = "pipeline-rtsp"
version = "0.1.0"
edition = "2024"

[dependencies]
glib = "0.21.3"
gstreamer = "0.24.2"
gstreamer-rtsp-server = "0.24.2"
anyhow = "1.0.100"
clap = { version = "4.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
ctrlc = "3.4"
