global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mediamtx'
    static_configs:
      - targets: ['paladium-mediamtx:9998']
    basic_auth:
      username: 'admin'
      password: 'admin'